debug: false
server:
  port: 3000
  servlet:
    context-path: /
  ssl:
    enabled: false
##    key-store-type: jks
##    key-store: classpath:keystore/nextlevel.jks
##    key-store-password: JustAnotherDB
##    key-alias: nextlevel
#      enabled: true
#      key-store-type: jks
#      key-store: classpath:keystore/nextlevel_keystore.jks
#      key-store-password: JustAnotherDB
##      key-password: JustAnotherDB
#      key-alias: intermediate

#trust:
#  store: classpath:keystore/nextlevel.p12
#    password: JustAnotherDB

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schoolmgmt_db_v1
    username: sm_user
    password: sm_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connectionTimeout: 30000
      idleTimeout: 60000
      maxLifetime: 60000
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: true


#  security:
#    oauth2:
#      client:
#        registration:
#         google:
#           clientId: <clientId>.apps.googleusercontent.com
#           clientSecret: <clientSecret>
#           scope:
#            - email
#            - profile
#
#         facebook:
#          clientId: <clientId>
#          clientSecret: <clientSecret>
#          scope:
#           - email
#           - public_profile

  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply_schoolmgmt@gmail.com
    password: <password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s

jwt:
  secret: <secret>
  header: Authorization
  # This token must be encoded using Base64 with mininum 88 Bits (you can type `echo 'secret-key'|base64` on your command line)
  base64-secret: <base64-secret>
  # token is valid 24 hours x 2
  token-validity-in-seconds: 172800
  # valid 24 hrs x 7 x 2
  token-validity-in-seconds-for-remember-me: 864000
  route:
    authentication:
      path: auth
      refresh: refresh

logging:
  level:
    org.nextlevel: INFO


kafka-config:
  topic: NEXTLEVEL_ES_REALTIME_METADATA_QUEUE_NAME
  bootstrap-server-host: localhost
  bootstrap-server-port: 9092




